# Generated by Django 5.1.6 on 2025-03-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('business_owner', 'Business Owner/Manager'), ('employee', 'Employee'), ('technical_staff', 'IT/Technical Staff')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role_selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
